### ISSUE TITLE
Please add support for newest 2.4.0 version that was released in Sep '14.

### ISSUE THREAD

**Issue by 01010000101001100** [dannygarcia/grunt-jekyll#68]
https://github.com/jekyll/jekyll/releases/tag/v2.4.0

**Comment by Martinsos** [comment]
How about asking guys from jekyll to take it over?

**Comment by jbutz** [comment]
When I flipped the `bundleExec` option to `true` I was able to get this working again. For whatever reason jekyll 2.4.0 and on doesn't seem to like being called without `bundle exec`

**Comment by brunowego** [comment]
+1

**Comment by sparanoid** [comment]
Seems working in the latest 3.0.0, anybody can test it again?

**Comment by johanbove** [comment]
@sparanoid I'm on Windows. Before upgrading today all was running perfectly. Having issues now with building and plugins since upgrading Jekyll to version 3.0.0; When I run "bundle exec jekyll serve" directly it works fine; but when I start Jekyll through "grunt-jekyll" I am getting this error; help appreciated;

```
Configuration file: _config.yml
Warning: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "jekyll build --source app --destination .jekyll/ --config _config.yml"
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-sitemap (LoadError)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:27:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:27:in `require_gems'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
        from C:/Ruby200-x64/bin/jekyll:23:in `load'
        from C:/Ruby200-x64/bin/jekyll:23:in `<main>'
 Use --force to continue.
```

**Comment by johanbove** [comment]
Update: setting the option "bundleExec" to true fixed the issue. :cool:
